--------------------------------------------------------
--  File created - Friday-July-22-2016   
--------------------------------------------------------
DROP TABLE "ORA1"."HCUSER";
DROP TABLE "ORA1"."HCCLASSES";
DROP TABLE "ORA1"."HCCLASSROOMS";
DROP TABLE "ORA1"."HCCLASSROSTER";
DROP TABLE "ORA1"."HCCOURSES";
DROP TABLE "ORA1"."HCINSTRUCTOR";
DROP TABLE "ORA1"."HCSTUDENTS";
--------------------------------------------------------
--  DDL for Table HCUSER
--------------------------------------------------------

  CREATE TABLE "ORA1"."HCUSER" 
   (	"USERID" NUMBER, 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HCCLASSES
--------------------------------------------------------

  CREATE TABLE "ORA1"."HCCLASSES" 
   (	"CRN" NUMBER, 
	"INSTRUCTORID" NUMBER, 
	"CLASSROOMID" NUMBER, 
	"COURSEID" NUMBER, 
	"SUBJECTCODE" NUMBER, 
	"TIMES" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HCCLASSROOMS
--------------------------------------------------------

  CREATE TABLE "ORA1"."HCCLASSROOMS" 
   (	"CLASSROOMID" NUMBER, 
	"BUILDINGNAME" VARCHAR2(50 BYTE), 
	"ROOMNUMBER" NUMBER, 
	"MAXCAPACITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HCCLASSROSTER
--------------------------------------------------------

  CREATE TABLE "ORA1"."HCCLASSROSTER" 
   (	"ROSTERID" NUMBER, 
	"STUDENTID" NUMBER, 
	"CRN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HCCOURSES
--------------------------------------------------------

  CREATE TABLE "ORA1"."HCCOURSES" 
   (	"COURSEID" NUMBER, 
	"DEPTNUMBER" NUMBER, 
	"COURSEDESCRIPTION" VARCHAR2(300 BYTE), 
	"COURSENAME" VARCHAR2(50 BYTE), 
	"SUBJECTCODE" NUMBER, 
	"CREDITS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HCINSTRUCTOR
--------------------------------------------------------

  CREATE TABLE "ORA1"."HCINSTRUCTOR" 
   (	"INSTRUCTORID" NUMBER, 
	"USERID" NUMBER, 
	"DEPTNUMBER" NUMBER, 
	"OFFICENUMBER" NUMBER, 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HCSTUDENTS
--------------------------------------------------------

  CREATE TABLE "ORA1"."HCSTUDENTS" 
   (	"STUDENTID" NUMBER, 
	"USERID" NUMBER, 
	"MAJOR" VARCHAR2(20 BYTE), 
	"ENTRYYEAR" VARCHAR2(50 BYTE), 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ORA1.HCUSER
SET DEFINE OFF;
Insert into ORA1.HCUSER (USERID,FIRSTNAME,LASTNAME,EMAIL,PASSWORD,USERNAME) values (11,'Joshua','Tucker','jptucker2009@gmail.com','password','Josh');
Insert into ORA1.HCUSER (USERID,FIRSTNAME,LASTNAME,EMAIL,PASSWORD,USERNAME) values (12,'Prof','Teach','pt@d.com','password','Prof');
REM INSERTING into ORA1.HCCLASSES
SET DEFINE OFF;
Insert into ORA1.HCCLASSES (CRN,INSTRUCTORID,CLASSROOMID,COURSEID,SUBJECTCODE,TIMES) values (1,1,1,1,1,'mtwtf 10');
Insert into ORA1.HCCLASSES (CRN,INSTRUCTORID,CLASSROOMID,COURSEID,SUBJECTCODE,TIMES) values (2,1,1,1,1,'mtwtf 3');
REM INSERTING into ORA1.HCCLASSROOMS
SET DEFINE OFF;
Insert into ORA1.HCCLASSROOMS (CLASSROOMID,BUILDINGNAME,ROOMNUMBER,MAXCAPACITY) values (1,'IT R&D',101,500);
REM INSERTING into ORA1.HCCLASSROSTER
SET DEFINE OFF;
Insert into ORA1.HCCLASSROSTER (ROSTERID,STUDENTID,CRN) values (2,1,1);
Insert into ORA1.HCCLASSROSTER (ROSTERID,STUDENTID,CRN) values (3,1,2);
REM INSERTING into ORA1.HCCOURSES
SET DEFINE OFF;
Insert into ORA1.HCCOURSES (COURSEID,DEPTNUMBER,COURSEDESCRIPTION,COURSENAME,SUBJECTCODE,CREDITS) values (1,1,'learn to program with java','Java101',1,4);
REM INSERTING into ORA1.HCINSTRUCTOR
SET DEFINE OFF;
Insert into ORA1.HCINSTRUCTOR (INSTRUCTORID,USERID,DEPTNUMBER,OFFICENUMBER,FIRSTNAME,LASTNAME) values (1,12,1,1,'Prof','Teach');
REM INSERTING into ORA1.HCSTUDENTS
SET DEFINE OFF;
Insert into ORA1.HCSTUDENTS (STUDENTID,USERID,MAJOR,ENTRYYEAR,FIRSTNAME,LASTNAME) values (1,11,'Science','2016','Joshua','Tucker');
--------------------------------------------------------
--  DDL for Index HCUSER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."HCUSER_PK" ON "ORA1"."HCUSER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HCCLASSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."HCCLASSES_PK" ON "ORA1"."HCCLASSES" ("CRN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HCCLASSROOMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."HCCLASSROOMS_PK" ON "ORA1"."HCCLASSROOMS" ("CLASSROOMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HCCLASSROSTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."HCCLASSROSTER_PK" ON "ORA1"."HCCLASSROSTER" ("ROSTERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HCCOURSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."HCCOURSES_PK" ON "ORA1"."HCCOURSES" ("COURSEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HCINSTRUCTOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."HCINSTRUCTOR_PK" ON "ORA1"."HCINSTRUCTOR" ("INSTRUCTORID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HCSTUDENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."HCSTUDENTS_PK" ON "ORA1"."HCSTUDENTS" ("STUDENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table HCUSER
--------------------------------------------------------

  ALTER TABLE "ORA1"."HCUSER" ADD CONSTRAINT "HCUSER_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."HCUSER" MODIFY ("USERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HCCLASSES
--------------------------------------------------------

  ALTER TABLE "ORA1"."HCCLASSES" MODIFY ("COURSEID" NOT NULL ENABLE);
  ALTER TABLE "ORA1"."HCCLASSES" ADD CONSTRAINT "HCCLASSES_PK" PRIMARY KEY ("CRN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."HCCLASSES" MODIFY ("CRN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HCCLASSROOMS
--------------------------------------------------------

  ALTER TABLE "ORA1"."HCCLASSROOMS" ADD CONSTRAINT "HCCLASSROOMS_PK" PRIMARY KEY ("CLASSROOMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."HCCLASSROOMS" MODIFY ("CLASSROOMID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HCCLASSROSTER
--------------------------------------------------------

  ALTER TABLE "ORA1"."HCCLASSROSTER" ADD CONSTRAINT "HCCLASSROSTER_PK" PRIMARY KEY ("ROSTERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."HCCLASSROSTER" MODIFY ("ROSTERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HCCOURSES
--------------------------------------------------------

  ALTER TABLE "ORA1"."HCCOURSES" ADD CONSTRAINT "HCCOURSES_PK" PRIMARY KEY ("COURSEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."HCCOURSES" MODIFY ("DEPTNUMBER" NOT NULL ENABLE);
  ALTER TABLE "ORA1"."HCCOURSES" MODIFY ("COURSEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HCINSTRUCTOR
--------------------------------------------------------

  ALTER TABLE "ORA1"."HCINSTRUCTOR" ADD CONSTRAINT "HCINSTRUCTOR_PK" PRIMARY KEY ("INSTRUCTORID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."HCINSTRUCTOR" MODIFY ("INSTRUCTORID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HCSTUDENTS
--------------------------------------------------------

  ALTER TABLE "ORA1"."HCSTUDENTS" ADD CONSTRAINT "HCSTUDENTS_PK" PRIMARY KEY ("STUDENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."HCSTUDENTS" MODIFY ("STUDENTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table HCCLASSES
--------------------------------------------------------

  ALTER TABLE "ORA1"."HCCLASSES" ADD CONSTRAINT "HCCLASSES_FK1" FOREIGN KEY ("INSTRUCTORID")
	  REFERENCES "ORA1"."HCINSTRUCTOR" ("INSTRUCTORID") ENABLE;
  ALTER TABLE "ORA1"."HCCLASSES" ADD CONSTRAINT "HCCLASSES_FK2" FOREIGN KEY ("COURSEID")
	  REFERENCES "ORA1"."HCCOURSES" ("COURSEID") ENABLE;
  ALTER TABLE "ORA1"."HCCLASSES" ADD CONSTRAINT "HCCLASSES_FK3" FOREIGN KEY ("CLASSROOMID")
	  REFERENCES "ORA1"."HCCLASSROOMS" ("CLASSROOMID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HCCLASSROSTER
--------------------------------------------------------

  ALTER TABLE "ORA1"."HCCLASSROSTER" ADD CONSTRAINT "HCCLASSROSTER_FK1" FOREIGN KEY ("CRN")
	  REFERENCES "ORA1"."HCCLASSES" ("CRN") ENABLE;
  ALTER TABLE "ORA1"."HCCLASSROSTER" ADD CONSTRAINT "HCCLASSROSTER_FK2" FOREIGN KEY ("STUDENTID")
	  REFERENCES "ORA1"."HCSTUDENTS" ("STUDENTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HCINSTRUCTOR
--------------------------------------------------------

  ALTER TABLE "ORA1"."HCINSTRUCTOR" ADD CONSTRAINT "HCINSTRUCTOR_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "ORA1"."HCUSER" ("USERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HCSTUDENTS
--------------------------------------------------------

  ALTER TABLE "ORA1"."HCSTUDENTS" ADD CONSTRAINT "HCSTUDENTS_FK1" FOREIGN KEY ("USERID")
	  REFERENCES "ORA1"."HCUSER" ("USERID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCUSER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORA1"."HCUSER_TRG" 
BEFORE INSERT ON HCUSER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.USERID IS NULL THEN
      SELECT HCUSER_SEQ.NEXTVAL INTO :NEW.USERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ORA1"."HCUSER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCCLASSES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORA1"."HCCLASSES_TRG" 
BEFORE INSERT ON HCCLASSES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CRN IS NULL THEN
      SELECT HCCLASSES_SEQ.NEXTVAL INTO :NEW.CRN FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ORA1"."HCCLASSES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCCLASSROOMS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORA1"."HCCLASSROOMS_TRG" 
BEFORE INSERT ON HCCLASSROOMS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CLASSROOMID IS NULL THEN
      SELECT HCCLASSROOMS_SEQ.NEXTVAL INTO :NEW.CLASSROOMID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ORA1"."HCCLASSROOMS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCCLASSROSTER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORA1"."HCCLASSROSTER_TRG" 
BEFORE INSERT ON HCCLASSROSTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ORA1"."HCCLASSROSTER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCCLASSROSTER_TRG1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORA1"."HCCLASSROSTER_TRG1" 
BEFORE INSERT ON HCCLASSROSTER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ROSTERID IS NULL THEN
      SELECT HCCLASSROSTER_SEQ1.NEXTVAL INTO :NEW.ROSTERID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ORA1"."HCCLASSROSTER_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCCOURSES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORA1"."HCCOURSES_TRG" 
BEFORE INSERT ON HCCOURSES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COURSEID IS NULL THEN
      SELECT HCCOURSES_SEQ.NEXTVAL INTO :NEW.COURSEID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ORA1"."HCCOURSES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCINSTRUCTOR_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORA1"."HCINSTRUCTOR_TRG" 
BEFORE INSERT ON HCINSTRUCTOR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.INSTRUCTORID IS NULL THEN
      SELECT HCINSTRUCTOR_SEQ.NEXTVAL INTO :NEW.INSTRUCTORID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ORA1"."HCINSTRUCTOR_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HCSTUDENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "ORA1"."HCSTUDENTS_TRG" 
BEFORE INSERT ON HCSTUDENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ORA1"."HCSTUDENTS_TRG" ENABLE;
